/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_DichVu;

import Controller.DichVuController;
import Help.ChuyenDoi;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class DichVuPnl extends javax.swing.JPanel {

    DichVuController dichVuController ;
    public static JPanel show ;
    QlDichVuPnl dichVu;
    private QlDichVuPnl quanDichVuPnl;
    private DanhmucVaDonViPnl danhmucVaDonViPnl;
    
    public DichVuPnl() {
        initComponents();
        addDichVu();
    }

    public void setController (DichVuController dichVuController) {
        this.dichVuController = dichVuController;
    }
    
    //Hiển thị panel
    public static void ShowPanel(JPanel PanelChua, JPanel panel) {
        show = panel;
        PanelChua.removeAll();
        PanelChua.add(show);
        PanelChua.validate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new swing.RoundPanel();
        roundPanel2 = new swing.RoundPanel();
        btnDichVu = new swing.Button();
        btnDanhMucDVT = new swing.Button();
        noiDungPnl = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        roundPanel1.setBackground(new java.awt.Color(218, 232, 232));
        roundPanel1.setPreferredSize(new java.awt.Dimension(1066, 786));

        roundPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnDichVu.setBackground(new java.awt.Color(83, 160, 203));
        btnDichVu.setText("DỊCH VỤ");
        btnDichVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichVuActionPerformed(evt);
            }
        });

        btnDanhMucDVT.setBackground(new java.awt.Color(120, 225, 220));
        btnDanhMucDVT.setText("DANH MỤC & ĐƠN VỊ TÍNH");
        btnDanhMucDVT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDanhMucDVT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhMucDVTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDanhMucDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(844, Short.MAX_VALUE))
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDanhMucDVT, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        noiDungPnl.setBackground(new java.awt.Color(218, 232, 232));
        noiDungPnl.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noiDungPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noiDungPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDanhMucDVTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhMucDVTActionPerformed
        danhmucVaDonViPnl = new DanhmucVaDonViPnl();
        DichVuController quanLyDichVuController = new DichVuController(danhmucVaDonViPnl);
        ShowPanel(noiDungPnl, danhmucVaDonViPnl);
        btnDanhMucDVT.setBackground(new Color(83,160,203));
        btnDichVu.setBackground(new Color(120,225,220));
    }//GEN-LAST:event_btnDanhMucDVTActionPerformed

    private void btnDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichVuActionPerformed
        addDichVu();
    }//GEN-LAST:event_btnDichVuActionPerformed
    
    public void addDichVu(){
        quanDichVuPnl = new QlDichVuPnl();
        DichVuController quanLyDichVuController = new DichVuController(quanDichVuPnl);
        ShowPanel(noiDungPnl, quanDichVuPnl);
        btnDichVu.setBackground(new Color(83,160,203));
        btnDanhMucDVT.setBackground(new Color(120,225,220));
    }


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btnDanhMucDVT;
    private swing.Button btnDichVu;
    private javax.swing.JPanel noiDungPnl;
    private swing.RoundPanel roundPanel1;
    private swing.RoundPanel roundPanel2;
    // End of variables declaration//GEN-END:variables
}
